# Generated by `devspec ci init`. Sourced from the pipeline/azuredevops fragment.
# Configurable bits live in .devspec/release.yaml — edit there, then rerun
# `devspec ci init --force`. This file is the deploy pipeline; CI gates live
# in azure-pipelines.yml.
#
# One-time Azure DevOps setup:
#   1. Pipelines → New pipeline → point at this azure-pipelines-release.yml
#      (name it "release").
#   2. Create a Docker registry service connection and set its name in the
#      dockerRegistryServiceConnection variable below.
#   3. Pipelines → Environments → create "staging" and "production"; add
#      Approvals and checks on "production" (required approvers). Approval is
#      controlled there, NOT in this YAML.
name: release

trigger:
  branches:
    include: [main]
  tags:
    include: ['v*.*.*']

pr: none

pool:
  vmImage: 'ubuntu-24.04'

variables:
  # ── Fill these in ────────────────────────────────────────────────────────
  dockerRegistryServiceConnection: 'REPLACE-ME-service-connection'
  containerRegistry: 'REPLACE-ME.azurecr.io'
  imageRepository: 'REPLACE-ME-app'
  # ─────────────────────────────────────────────────────────────────────────
  imageTag: 'sha-$(Build.SourceVersion)'
  fullImage: '$(containerRegistry)/$(imageRepository):$(imageTag)'

stages:
  - stage: Build
    displayName: build + push image
    jobs:
      - job: build
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Build and push image
            inputs:
              command: buildAndPush
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageRepository)
              dockerfile: Dockerfile
              tags: |
                $(imageTag)
                $(Build.SourceBranchName)

  - stage: DeployStaging
    displayName: deploy → staging
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: deploy_staging
        displayName: staging
        environment: staging
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - script: docker compose run --rm dev sh -c "$DEVSPEC_CMD"
                  displayName: Validate (pre-deploy)
                  env:
                    DEVSPEC_CMD: |-
                      {{ release.environments.staging.validate_cmd }}

                - script: |
                    {{ release.environments.staging.deploy_cmd }}
                  displayName: Deploy
                  env:
                    IMAGE_TAG: $(fullImage)

                - script: |
                    {{ release.environments.staging.smoke_cmd }}
                  displayName: Post-deploy smoke test
                  env:
                    DEPLOY_URL: {{ release.environments.staging.url }}

  - stage: DeployProduction
    displayName: deploy → production
    dependsOn: Build
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
    jobs:
      - deployment: deploy_production
        displayName: production
        # Approvals and checks on the "production" Environment gate this job.
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - script: docker compose run --rm dev sh -c "$DEVSPEC_CMD"
                  displayName: Validate (pre-deploy)
                  env:
                    DEVSPEC_CMD: |-
                      {{ release.environments.production.validate_cmd }}

                - script: |
                    {{ release.environments.production.deploy_cmd }}
                  displayName: Deploy
                  env:
                    IMAGE_TAG: $(fullImage)

                - script: |
                    {{ release.environments.production.smoke_cmd }}
                  displayName: Post-deploy smoke test
                  env:
                    DEPLOY_URL: {{ release.environments.production.url }}
