# Generated by `devspec ci init`. Sourced from the pipeline/azuredevops fragment.
# To customize, edit src/packs/pipeline/azuredevops/templates/workflow.yml.tpl and rerun.
#
# One-time Azure DevOps setup after committing this file:
#   1. Pipelines → New pipeline → point at this azure-pipelines.yml (name it "ci").
#   2. Project Settings → Repositories → <repo> → Policies → main:
#      add a Build Validation policy requiring the "ci" pipeline,
#      plus minimum 1 reviewer, comment resolution, and linked work items.
name: ci

trigger:
  batch: true
  branches:
    include: [main]

pr:
  branches:
    include: [main]

pool:
  vmImage: 'ubuntu-24.04'

variables:
  DOCKER_BUILDKIT: '1'

jobs:
  - job: security
    displayName: security
    steps:
      - checkout: self
        fetchDepth: 0

      - script: >
          docker run --rm -v "$(Build.SourcesDirectory):/repo"
          zricethezav/gitleaks:latest detect --source /repo --no-banner --redact
        displayName: Secret scan (gitleaks)

      - script: |
          docker compose build dev
          docker compose run --rm dev sh -c "$DEVSPEC_CMD"
        displayName: Dependency audit
        env:
          DEVSPEC_CMD: |-
            {{ backend.commands.audit }}

  - job: quality
    displayName: quality
    steps:
      - checkout: self

      - script: docker compose build dev
        displayName: Build dev image

      - script: docker compose run --rm dev sh -c "$DEVSPEC_CMD"
        displayName: Format check
        env:
          DEVSPEC_CMD: |-
            {{ backend.commands.format_check }}

      - script: docker compose run --rm dev sh -c "$DEVSPEC_CMD"
        displayName: Lint (warnings as errors)
        env:
          DEVSPEC_CMD: |-
            {{ backend.commands.lint }}

      - script: docker compose run --rm dev sh -c "$DEVSPEC_CMD"
        displayName: Typecheck
        env:
          DEVSPEC_CMD: |-
            {{ backend.commands.typecheck }}

  - job: test_unit
    displayName: test-unit
    steps:
      - checkout: self

      - script: docker compose build dev
        displayName: Build dev image

      - script: docker compose run --rm dev sh -c "$DEVSPEC_CMD"
        displayName: Run unit tests
        env:
          DEVSPEC_CMD: |-
            {{ backend.commands.test_unit }}

  - job: test_integration
    displayName: test-integration
    steps:
      - checkout: self

      - script: docker compose build dev
        displayName: Build dev image

      - script: docker compose run --rm dev sh -c "$DEVSPEC_CMD"
        displayName: Run integration tests
        env:
          DEVSPEC_CMD: |-
            {{ backend.commands.test_integration }}

  - job: test_e2e
    displayName: test-e2e
    condition: eq('{{ has_frontend }}', 'true')
    steps:
      - checkout: self

      - task: NodeTool@0
        displayName: Use Node 22
        inputs:
          versionSpec: '22.x'

      - script: npm ci
        displayName: Install dependencies

      - script: npx playwright install --with-deps chromium
        displayName: Install Playwright browsers

      - script: "{{ frontend.commands.build }}"
        displayName: Build app

      - script: "{{ frontend.commands.test_e2e }}"
        displayName: Run E2E tests

      - task: PublishPipelineArtifact@1
        displayName: Upload Playwright report on failure
        condition: failed()
        inputs:
          targetPath: playwright-report
          artifact: playwright-report

  - job: devspec
    displayName: devspec
    steps:
      - checkout: self
        fetchDepth: 0

      - task: NodeTool@0
        displayName: Use Node 22
        inputs:
          versionSpec: '22.x'

      # Install devspec. Defaults to the published npm package. Pin a version
      # (devspec-cli@x.y.z) or switch to a git/source install if you need to.
      - script: npm install -g devspec-cli
        displayName: Install devspec

      - script: devspec doctor
        displayName: devspec doctor

      - script: devspec check
        displayName: devspec check

      - bash: |
          set -e
          shopt -s nullglob
          mkdir -p .devspec-sarif
          had_drift=0
          for dir in .devspec/projects/*/; do
            slug="$(basename "$dir")"
            echo "##[group]coherence $slug"
            if ! devspec coherence "$slug" --json --block-only --sarif ".devspec-sarif/$slug.sarif" > /dev/null; then
              echo "##vso[task.logissue type=error]DevSpec drift in $slug — run 'devspec coherence $slug' locally to see details."
              had_drift=1
            fi
            echo "##[endgroup]"
          done
          if [ "$had_drift" -ne 0 ]; then
            exit 1
          fi
        displayName: Coherence per active change

      # The "CodeAnalysisLogs" artifact name is the convention the
      # "SARIF SAST Scans Tab" marketplace extension reads — install it to get
      # findings rendered in a Scans tab on the run. Without the extension the
      # artifact is still downloadable; the ##vso error annotations above work
      # regardless.
      - task: PublishPipelineArtifact@1
        displayName: Publish coherence SARIF
        condition: always()
        continueOnError: true
        inputs:
          targetPath: .devspec-sarif
          artifact: CodeAnalysisLogs

      - script: devspec phase || true
        displayName: Workspace phase (informational)
        condition: always()
