# Generated by `devspec ci init`. Sourced from the pipeline/github fragment.
# Configurable bits live in .devspec/release.yaml — edit there, not here.
# This file is the deploy pipeline. The CI gates live in ci.yml.
name: release

on:
  push:
    branches: [main]
    tags: ['v*.*.*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    name: build + push image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    outputs:
      image: ${{ steps.meta.outputs.tags }}
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image tags + labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,format=long,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-staging:
    name: deploy → staging
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    environment:
      name: staging
      url: {{ release.environments.staging.url }}
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4

      - name: Validate (pre-deploy)
        run: docker compose run --rm dev sh -c "$DEVSPEC_CMD"
        env:
          DEVSPEC_CMD: |-
            {{ release.environments.staging.validate_cmd }}

      - name: Deploy
        run: |
          {{ release.environments.staging.deploy_cmd }}
        env:
          IMAGE_TAG: ${{ needs.build.outputs.image }}

      - name: Post-deploy smoke test
        run: |
          {{ release.environments.staging.smoke_cmd }}
        env:
          DEPLOY_URL: {{ release.environments.staging.url }}

  deploy-production:
    name: deploy → production
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-24.04
    # The 'production' environment in GitHub Settings → Environments controls
    # who can approve this job. Configure required reviewers there, NOT here.
    environment:
      name: production
      url: {{ release.environments.production.url }}
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4

      - name: Validate (pre-deploy)
        run: docker compose run --rm dev sh -c "$DEVSPEC_CMD"
        env:
          DEVSPEC_CMD: |-
            {{ release.environments.production.validate_cmd }}

      - name: Deploy
        run: |
          {{ release.environments.production.deploy_cmd }}
        env:
          IMAGE_TAG: ${{ needs.build.outputs.image }}

      - name: Post-deploy smoke test
        run: |
          {{ release.environments.production.smoke_cmd }}
        env:
          DEPLOY_URL: {{ release.environments.production.url }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ github.ref_name }}
