# Generated by `devspec ci init`. Sourced from the pipeline/github fragment.
# To customize, edit src/packs/pipeline/github/templates/workflow.yml.tpl and rerun.
# The install step needs your config (see comment block in the `devspec` job).
name: ci

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  security:
    name: security
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secret scan (gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dependency review
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          comment-summary-in-pr: on-failure

  quality:
    name: quality
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build dev image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: devspec-dev:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Format check
        run: docker compose run --rm dev sh -c "$DEVSPEC_CMD"
        env:
          DEVSPEC_CMD: |-
            {{ backend.commands.format_check }}

      - name: Lint (warnings as errors)
        run: docker compose run --rm dev sh -c "$DEVSPEC_CMD"
        env:
          DEVSPEC_CMD: |-
            {{ backend.commands.lint }}

      - name: Typecheck
        run: docker compose run --rm dev sh -c "$DEVSPEC_CMD"
        env:
          DEVSPEC_CMD: |-
            {{ backend.commands.typecheck }}

  test-unit:
    name: test-unit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build dev image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: devspec-dev:ci
          cache-from: type=gha

      - name: Run unit tests
        run: docker compose run --rm dev sh -c "$DEVSPEC_CMD"
        env:
          DEVSPEC_CMD: |-
            {{ backend.commands.test_unit }}

  test-integration:
    name: test-integration
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build dev image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: devspec-dev:ci
          cache-from: type=gha

      - name: Run integration tests
        run: docker compose run --rm dev sh -c "$DEVSPEC_CMD"
        env:
          DEVSPEC_CMD: |-
            {{ backend.commands.test_integration }}

  test-e2e:
    name: test-e2e
    runs-on: ubuntu-24.04
    if: {{ has_frontend }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Build app
        run: "{{ frontend.commands.build }}"

      - name: Run E2E tests
        run: "{{ frontend.commands.test_e2e }}"

      - name: Upload Playwright report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

  devspec:
    name: devspec
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      # ─────────────────────────────────────────────────────────────────────
      # Install devspec — CHOOSE ONE and delete the rest. The default exits
      # with a clear error so this workflow can't silently pass without
      # actually running devspec.
      # ─────────────────────────────────────────────────────────────────────
      - name: Install devspec
        run: |
          # Option 1 — from npm (once devspec is published):
          # npm install -g devspec
          #
          # Option 2 — from a git source (devspec repo, branch or tag):
          # npm install -g github:YOUR_ORG/devspec#main
          #
          # Option 3 — from source clone + build:
          # git clone --depth 1 --branch main https://github.com/YOUR_ORG/devspec /tmp/devspec
          # cd /tmp/devspec && npm ci && npm run build && npm link
          echo "::error::Edit .github/workflows/ci.yml and choose a devspec install method"
          exit 1

      - name: devspec doctor
        run: devspec doctor

      - name: devspec check
        run: devspec check

      - name: Coherence per active change
        run: |
          set -e
          shopt -s nullglob
          had_drift=0
          for dir in .devspec/projects/*/; do
            slug="$(basename "$dir")"
            echo "::group::coherence $slug"
            if ! devspec coherence "$slug" --json --block-only > /dev/null; then
              echo "::error title=DevSpec drift in $slug::Run \`devspec coherence $slug\` locally to see details."
              had_drift=1
            fi
            echo "::endgroup::"
          done
          if [ "$had_drift" -ne 0 ]; then
            exit 1
          fi

      - name: Workspace phase (informational)
        if: always()
        run: devspec phase || true
