import path from "node:path";
import { Command } from "commander";
import chalk from "chalk";
import fs from "fs-extra";
import YAML from "yaml";
import { requireWorkspaceRoot, devspecPath } from "../core/workspace.js";
import { readDevspecConfig } from "../core/config.js";
import { nextStep } from "../core/hints.js";

export const envCommand = new Command("env")
  .description("Generate or inspect the development environment");

envCommand
  .command("generate")
  .description("Generate editor files, devcontainer, AND a plain Dockerfile + docker-compose.yml for containerized builds/tests")
  .option("--force", "Overwrite existing files", false)
  .action(async (options: { force: boolean }) => {
    const root = await requireWorkspaceRoot();
    const devEnvPath = devspecPath(root, "company", "dev-environment.yaml");

    if (!(await fs.pathExists(devEnvPath))) {
      console.error(
        chalk.red(
          `No dev-environment.yaml found at ${path.relative(root, devEnvPath)}. Re-run \`devspec init\` with a backend that ships one.`
        )
      );
      process.exitCode = 1;
      return;
    }

    const devEnv = YAML.parse(await fs.readFile(devEnvPath, "utf8")) ?? {};
    const config = await readDevspecConfig(root);

    const targets: { rel: string; content: string | object }[] = [];

    if (devEnv.vscode?.settings) {
      targets.push({
        rel: ".vscode/settings.json",
        content: devEnv.vscode.settings,
      });
    }
    if (devEnv.vscode?.extensions) {
      targets.push({
        rel: ".vscode/extensions.json",
        content: { recommendations: devEnv.vscode.extensions },
      });
    }
    if (devEnv.vscode?.tasks) {
      targets.push({
        rel: ".vscode/tasks.json",
        content: { version: "2.0.0", tasks: devEnv.vscode.tasks },
      });
    }
    if (devEnv.devcontainer) {
      targets.push({
        rel: ".devcontainer/devcontainer.json",
        content: devEnv.devcontainer,
      });
    }

    // Derive a plain Dockerfile + docker-compose.yml from the devcontainer image.
    // This is what makes `devspec run` work — it lets agents (and humans) execute
    // commands in a reproducible container without writing any Docker themselves.
    const dockerFiles = renderDockerFiles(config.backend, devEnv);
    if (dockerFiles) {
      targets.push({ rel: "Dockerfile", content: dockerFiles.dockerfile });
      targets.push({ rel: "docker-compose.yml", content: dockerFiles.compose });
      targets.push({ rel: ".dockerignore", content: dockerFiles.dockerignore });
    }

    if (targets.length === 0) {
      console.log(chalk.yellow("dev-environment.yaml defines no targets."));
      return;
    }

    let written = 0;
    let skipped = 0;

    for (const target of targets) {
      const abs = path.join(root, target.rel);
      if ((await fs.pathExists(abs)) && !options.force) {
        console.log(chalk.yellow(`  skip   ${target.rel} (exists, use --force)`));
        skipped++;
        continue;
      }
      await fs.ensureDir(path.dirname(abs));
      const body =
        typeof target.content === "string"
          ? target.content
          : JSON.stringify(target.content, null, 2) + "\n";
      await fs.writeFile(abs, body);
      console.log(chalk.green(`  write  ${target.rel}`));
      written++;
    }

    console.log("");
    console.log(`Done. ${written} written, ${skipped} skipped.`);
    if (written > 0) {
      console.log("");
      console.log(chalk.dim("Docker is optional:"));
      console.log(
        chalk.dim("  • install Docker if you want reproducible commands across machines/CI") +
          chalk.dim(" — then ") +
          chalk.cyan("devspec run cargo test") +
          chalk.dim(" (or pytest/dotnet/npm) runs in the container")
      );
      console.log(
        chalk.dim("  • skip Docker if developing locally — ") +
          chalk.cyan("devspec run --local <cmd>") +
          chalk.dim(" or just run the command directly")
      );
      console.log("");
      nextStep("reload your editor to pick up the new settings");
    }
  });

interface DockerFiles {
  dockerfile: string;
  compose: string;
  dockerignore: string;
}

function renderDockerFiles(
  backend: string,
  devEnv: Record<string, unknown>
): DockerFiles | null {
  const dc = devEnv.devcontainer as Record<string, unknown> | undefined;
  if (!dc || typeof dc.image !== "string") return null;
  const image = dc.image as string;
  const postCreate = typeof dc.postCreateCommand === "string"
    ? (dc.postCreateCommand as string).trim()
    : null;

  const dockerfileLines = [
    `# Generated by \`devspec env generate\`. Edit freely — re-run with --force to regenerate.`,
    `FROM ${image}`,
    "",
    `WORKDIR /workspace`,
  ];
  if (postCreate) {
    dockerfileLines.push("");
    dockerfileLines.push(`# postCreateCommand from dev-environment.yaml`);
    dockerfileLines.push(`RUN ${postCreate.replace(/\n/g, " && ")} || true`);
  }
  dockerfileLines.push("");
  dockerfileLines.push(`# Default to an interactive shell so \`docker run\` is debuggable.`);
  dockerfileLines.push(`# Production builds use multi-stage compose targets instead.`);
  dockerfileLines.push(`CMD ["bash"]`);

  const composeLines = [
    `# Generated by \`devspec env generate\`. \`devspec run <cmd>\` shells into the dev service.`,
    `services:`,
    `  dev:`,
    `    build: .`,
    `    image: devspec-${backend}-dev`,
    `    volumes:`,
    `      - .:/workspace`,
    `    working_dir: /workspace`,
    `    command: bash`,
    `    stdin_open: true`,
    `    tty: true`,
    ``,
    `  test:`,
    `    build: .`,
    `    volumes:`,
    `      - .:/workspace`,
    `    working_dir: /workspace`,
    `    command: ${defaultTestCommand(backend)}`,
  ];

  const dockerignoreLines = [
    `node_modules`,
    `target`,
    `bin`,
    `obj`,
    `dist`,
    `.git`,
    `.devspec`,
    `.vscode`,
    `.devcontainer`,
    `__pycache__`,
    `.pytest_cache`,
    `.mypy_cache`,
    `.venv`,
    `coverage`,
    `*.log`,
  ];

  return {
    dockerfile: dockerfileLines.join("\n") + "\n",
    compose: composeLines.join("\n") + "\n",
    dockerignore: dockerignoreLines.join("\n") + "\n",
  };
}

function defaultTestCommand(backend: string): string {
  switch (backend) {
    case "rust":
      return "cargo test";
    case "dotnet":
      return "dotnet test --nologo";
    case "node-typescript":
      return "npm test";
    case "python":
      return "pytest";
    default:
      return "echo 'no default test command for backend " + backend + "'";
  }
}
