import { Command } from "commander";
import chalk from "chalk";

export const guideCommand = new Command("guide")
  .description("Print the DevSpec mental model — lifecycle, phases, and command map")
  .action(() => {
    const c = chalk.cyan;
    const b = chalk.bold;
    const d = chalk.dim;

    console.log(b("DevSpec — spec-driven engineering standards and guardrails"));
    console.log("");
    console.log(b("CORE IDEA"));
    console.log("  Every change walks through a lifecycle of artifacts;");
    console.log("  the workspace as a whole progresses through phases.");
    console.log("  DevSpec checks these stay in sync — no drift between spec and code.");
    console.log("");

    console.log(b("LIFECYCLE — per change") + d(" (.devspec/projects/<slug>/)"));
    console.log(`  ${c("discovery")}   ${d("what problem are we solving, for whom?")}`);
    console.log(`  ${c("proposal")}    ${d("what are we doing about it?")}`);
    console.log(`  ${c("design")}      ${d("what does the solution look like (high-level)?")}`);
    console.log(`  ${c("contract")}    ${d("TS-flavored pseudocode + machine-readable test list")}`);
    console.log(`  ${c("alignment")}   ${d("stakeholder sign-off, decisions captured")}`);
    console.log(`  ${c("tasks")}       ${d("implementation breakdown, TDD-driven")}`);
    console.log("");

    console.log(b("PHASES — workspace-wide"));
    console.log(`  ${c("sketch")}      ${d("workspace exists, exploration in progress")}`);
    console.log(`  ${c("design")}      ${d("first change has a settled design")}`);
    console.log(`  ${c("contract")}    ${d("first contract with tests is written")}`);
    console.log(`  ${c("build")}       ${d("tests scaffolded into source, implementation underway")}`);
    console.log(`  ${c("ready")}       ${d("all tests pass, coherence is clean")}`);
    console.log(`  ${c("uat")}         ${d("UAT criteria defined, validation in progress")}`);
    console.log(`  ${c("production")}  ${d("all UAT passed; declared in devspec.yaml; strict mode on")}`);
    console.log("");

    console.log(b("COMMANDS BY TASK"));
    console.log("");
    console.log(`  ${d("Starting a workspace")}`);
    console.log(`    ${c("devspec init --backend <b> [--frontend <f>] --architecture <a> --methodology <m> [--infrastructure <i>]")}`);
    console.log(`    ${c("devspec env generate")}                ${d("write .vscode/, devcontainer, Dockerfile + docker-compose.yml")}`);
    console.log(`    ${c("devspec run <cmd>")}                   ${d("run any command in the workspace container (auto if Docker present)")}`);
    console.log("");
    console.log(`    ${d("Axes available")} ${d("(drop a folder under src/packs/<axis>/<name>/ to add more)")}`);
    console.log(`      ${d("backend         ")} dotnet, node-typescript, rust, python`);
    console.log(`      ${d("frontend        ")} svelte, blazor    ${d("(optional)")}`);
    console.log(`      ${d("architecture    ")} clean-architecture, layered, vertical-slice`);
    console.log(`      ${d("methodology     ")} ddd, tdd, bdd, lightweight`);
    console.log(`      ${d("infrastructure  ")} kubernetes, terraform    ${d("(optional)")}`);
    console.log("");
    console.log(`  ${d("Working on a change")}`);
    console.log(`    ${c("devspec plan \"<title>\"")}              ${d("scaffold the 6 lifecycle docs")}`);
    console.log(`    ${c("devspec scaffold <slug>")}             ${d("emit failing test stubs in your backend")}`);
    console.log(`    ${c("devspec next <slug>")}                 ${d("show the next unchecked task")}`);
    console.log(`    ${c("devspec complete <slug> <match>")}     ${d("tick off a task in tasks.md")}`);
    console.log(`    ${c("devspec advance <slug> <stage>")}      ${d("mark a lifecycle stage done")}`);
    console.log("");
    console.log(`  ${d("Checking drift")}`);
    console.log(`    ${c("devspec coherence <slug>")}            ${d("artifact-to-artifact drift check")}`);
    console.log(`    ${c("devspec check")}                       ${d("workspace + architecture guardrails")}`);
    console.log(`    ${c("devspec doctor")}                      ${d("diagnose setup problems")}`);
    console.log("");
    console.log(`  ${d("Seeing where you are")}`);
    console.log(`    ${c("devspec status")}                      ${d("all changes + workspace phase line")}`);
    console.log(`    ${c("devspec phase")}                       ${d("phase detail with gates and next steps")}`);
    console.log("");
    console.log(`  ${d("UAT")}`);
    console.log(`    ${c("devspec uat init")}                    ${d("scaffold uat.yaml")}`);
    console.log(`    ${c("devspec uat list")}                    ${d("criteria + statuses")}`);
    console.log(`    ${c("devspec uat pass <name> --by")}        ${d("record sign-off")}`);
    console.log(`    ${c("devspec uat fail <name> --note")}      ${d("record failure with reason")}`);
    console.log("");
    console.log(`  ${d("Going backward")}`);
    console.log(`    ${c("devspec rewind <slug> <stage>")}       ${d("regress a change, log reason to alignment.md")}`);
    console.log(`    ${c("devspec phase --set <earlier>")}       ${d("force the workspace to an earlier phase")}`);
    console.log("");
    console.log(`  ${d("Parallel-agent isolation (git worktrees)")}`);
    console.log(`    ${c("devspec worktree add <slug>")}         ${d("create .devspec/worktrees/<slug>/ on branch devspec/<slug>")}`);
    console.log(`    ${c("devspec worktree list")}               ${d("see all per-change worktrees")}`);
    console.log(`    ${c("devspec worktree remove <slug>")}      ${d("clean up a worktree (and optionally its branch)")}`);
    console.log("");
    console.log(`  ${d("CI integration")}`);
    console.log(`    ${c("devspec ci init")}                     ${d("write .github/workflows/devspec.yml + PR template (GitHub Actions)")}`);
    console.log("");
    console.log(`  ${d("Production handoff")}`);
    console.log(`    ${c("devspec phase --set production")}      ${d("declare production; warnings become blocks")}`);
    console.log(`    ${c("devspec phase --auto")}                ${d("clear the declaration, revert to detection")}`);
    console.log("");
    console.log(`  ${d("Recording decisions")}`);
    console.log(`    ${c("devspec log <slug> \"<decision>\"")}     ${d("append timestamped entry to alignment.md")}`);
    console.log("");
    console.log(`  ${d("Ralph loop (Claude Code)")}`);
    console.log(`    ${c("/loop /devspec:iterate <slug>")}        ${d("autonomous implement + review iteration for one change")}`);
    console.log(`    ${c("/loop /devspec:iterate-all [slugs]")}   ${d("rotate fairly across multiple active changes (single-window)")}`);
    console.log(`    ${c("/devspec:review <slug>")}               ${d("standalone PR-style review in fresh subagent")}`);
    console.log(`    ${c("/devspec:coordinate [slugs]")}          ${d("cross-change conflict detection (run when multiple changes are in flight)")}`);
    console.log(`    ${c("/devspec:refresh-standards <axis/name>")} ${d("re-verify versions/idioms against live web sources")}`);
    console.log("");
    console.log(`  ${d("Skills (Claude Code conversational patterns)")}`);
    console.log(`    ${c("devspec-onboard")}                       ${d("first-time walkthrough: pick axes, init, plan first change")}`);
    console.log(`    ${c("devspec-grill <slug> [stage]")}          ${d("stage-aware interview that drafts a lifecycle doc")}`);
    console.log(`    ${c("devspec-uat-design")}                    ${d("interview to write workspace UAT criteria before production")}`);
    console.log(`    ${c("devspec-triage")}                        ${d("walk coherence findings, fix/suppress/defer per finding")}`);
    console.log("");

    console.log(b("WHO OWNS WHAT IN A CHANGE"));
    console.log("");
    console.log(`  ${c("contract.md")} ${d("(the ```yaml tests block)")}`);
    console.log(`    ${d("The source of truth for what to build. Each test entry becomes a failing")}`);
    console.log(`    ${d("function in source via ")}${c("devspec scaffold")}${d(". Drives test-driven implementation.")}`);
    console.log("");
    console.log(`  ${c("tasks.md")}`);
    console.log(`    ${d("Work that is NOT a contract test: docs, migrations, deployment, configuration,")}`);
    console.log(`    ${d("coordination. If you can write it as a test, it goes in contract.md instead.")}`);
    console.log("");
    console.log(`  ${c("source code")}`);
    console.log(`    ${d("Implements what the contract specifies. Coherence rules verify the link")}`);
    console.log(`    ${d("between contract and source — see ")}${c("devspec coherence <slug>")}${d(".")}`);
    console.log("");

    console.log(b("THE TYPICAL FLOW"));
    console.log("");
    console.log(`  ${d("1.")} ${c("devspec init")} ${d("→ sets up workspace, picks backend/architecture/methodology")}`);
    console.log(`  ${d("2.")} ${c("devspec env generate")} ${d("→ writes editor + devcontainer files")}`);
    console.log(`  ${d("3.")} ${c("devspec plan \"My change\"")} ${d("→ creates the 6 lifecycle docs")}`);
    console.log(`  ${d("4.")} ${d("Fill in discovery → proposal → design → contract (pseudocode + tests YAML)")}`);
    console.log(`  ${d("5.")} ${c("devspec scaffold <slug>")} ${d("→ emits failing tests in target language")}`);
    console.log(`  ${d("6.")} ${d("Make each failing test pass. Use tasks.md for non-test work (docs, deploy).")}`);
    console.log(`     ${d("Until")} ${c("devspec check")} ${d("and")} ${c("devspec coherence")} ${d("are both clean.")}`);
    console.log(`  ${d("7.")} ${c("devspec uat init")} ${d("→ define acceptance criteria")}`);
    console.log(`  ${d("8.")} ${d("Validate; ")}${c("devspec uat pass <name>")} ${d("for each criterion")}`);
    console.log(`  ${d("9.")} ${c("devspec phase --set production")} ${d("→ enable strict mode")}`);
    console.log("");

    console.log(b("WHEN THINGS GO WRONG"));
    console.log(`  ${c("devspec doctor")}              ${d("diagnose workspace setup")}`);
    console.log(`  ${c("devspec phase")}               ${d("shows what's blocking the next phase")}`);
    console.log(`  ${c("devspec coherence <slug>")}    ${d("shows artifact drift for one change")}`);
    console.log("");

    console.log(d("Run any command with --help for its flags."));
  });
