import path from "node:path";
import { Command } from "commander";
import chalk from "chalk";
import fs from "fs-extra";
import { requireWorkspaceRoot } from "../core/workspace.js";
import { readDevspecConfig } from "../core/config.js";
import { loadChangeState } from "../core/change.js";
import type { TestSpec } from "../core/coherence/types.js";
import { pascalCase, snakeCase } from "../core/templates.js";
import { cmd, nextStep } from "../core/hints.js";

type Target = "rust" | "dotnet" | "go";

const SUPPORTED_TARGETS: Target[] = ["rust", "dotnet", "go"];

const DEFAULT_WRITE_PATHS: Record<Target, (slug: string) => string> = {
  rust: (slug) => `tests/${snakeCase(slug)}_tests.rs`,
  dotnet: (slug) => `tests/${pascalCase(slug)}Tests.cs`,
  go: (slug) => `${snakeCase(slug)}_test.go`,
};

export const scaffoldCommand = new Command("scaffold")
  .description("Emit failing test skeletons in the target language from contract tests")
  .argument("<slug>", "Change slug")
  .option(
    "--target <name>",
    `Target language: ${SUPPORTED_TARGETS.join(", ")} (defaults to workspace backend)`
  )
  .option(
    "--write <path>",
    "Write to a file (defaults to tests/<slug>_tests.<ext> for the target). Pass --stdout to print instead."
  )
  .option("--stdout", "Print to stdout instead of writing a file", false)
  .action(async (slug: string, options: { target?: string; write?: string; stdout: boolean }) => {
    const root = await requireWorkspaceRoot();
    const config = await readDevspecConfig(root);
    const target = (options.target ?? config.backend) as Target;

    if (!SUPPORTED_TARGETS.includes(target)) {
      console.error(
        chalk.red(
          `Unsupported scaffold target "${target}". Supported: ${SUPPORTED_TARGETS.join(", ")}`
        )
      );
      process.exitCode = 1;
      return;
    }

    const state = await loadChangeState(root, slug);
    if (state.tests.length === 0) {
      console.error(
        chalk.red(
          `No tests found in ${path.relative(root, state.docs.contract.path)}. Add a \`\`\`yaml tests block.`
        )
      );
      process.exitCode = 1;
      return;
    }

    const output =
      target === "rust"
        ? renderRust(slug, state.tests)
        : target === "go"
        ? renderGo(slug, state.tests)
        : renderDotnet(slug, state.tests);

    if (options.stdout) {
      process.stdout.write(output);
      return;
    }

    const writePath = options.write ?? DEFAULT_WRITE_PATHS[target](slug);
    const abs = path.resolve(root, writePath);
    if (await fs.pathExists(abs)) {
      console.error(
        chalk.red(
          `${path.relative(root, abs)} already exists. Pass --write <path> for a different location, or --stdout to print instead.`
        )
      );
      process.exitCode = 1;
      return;
    }
    await fs.ensureDir(path.dirname(abs));
    await fs.writeFile(abs, output);
    console.log(
      chalk.green(`Wrote ${state.tests.length} test stub(s) to ${path.relative(root, abs)}`)
    );
    console.log("");
    nextStep(
      `implement the failing tests, then ${cmd("devspec check")} and ${cmd(`devspec coherence ${slug}`)}`
    );
  });

function renderRust(slug: string, tests: TestSpec[]): string {
  const moduleName = snakeCase(slug);
  const lines: string[] = [
    `// Generated by \`devspec scaffold ${slug} --target rust\``,
    `// Edit freely after generation — re-running scaffold will not preserve changes.`,
    "",
    `#[cfg(test)]`,
    `mod ${moduleName}_tests {`,
    "",
  ];
  for (const t of tests) {
    const fnName = snakeCase(t.name);
    lines.push(`    #[test]`);
    lines.push(`    fn ${fnName}() {`);
    if (t.given.length > 0) {
      lines.push(`        // given:`);
      for (const g of t.given) lines.push(`        //   - ${g}`);
    }
    lines.push(`        // when: ${t.when}`);
    lines.push(`        // then: ${t.then}`);
    lines.push(`        todo!("implement");`);
    lines.push(`    }`);
    lines.push("");
  }
  lines.push(`}`);
  lines.push("");
  return lines.join("\n");
}

function renderGo(slug: string, tests: TestSpec[]): string {
  const pkg = snakeCase(slug).replace(/-/g, "_");
  const lines: string[] = [
    `// Generated by \`devspec scaffold ${slug} --target go\``,
    `// Edit freely after generation — re-running scaffold will not preserve changes.`,
    "",
    `package ${pkg}_test`,
    "",
    `import "testing"`,
    "",
  ];
  for (const t of tests) {
    const fnName = "Test" + pascalCase(t.name);
    lines.push(`func ${fnName}(t *testing.T) {`);
    if (t.given.length > 0) {
      lines.push(`    // given:`);
      for (const g of t.given) lines.push(`    //   - ${g}`);
    }
    lines.push(`    // when: ${t.when}`);
    lines.push(`    // then: ${t.then}`);
    lines.push(`    t.Fatal("not implemented")`);
    lines.push(`}`);
    lines.push("");
  }
  return lines.join("\n");
}

function renderDotnet(slug: string, tests: TestSpec[]): string {
  const className = `${pascalCase(slug)}Tests`;
  const lines: string[] = [
    `// Generated by \`devspec scaffold ${slug} --target dotnet\``,
    `// Edit freely after generation — re-running scaffold will not preserve changes.`,
    "",
    `using Xunit;`,
    "",
    `public class ${className}`,
    `{`,
  ];
  for (const t of tests) {
    const methodName = pascalCase(t.name) || "Test";
    lines.push(`    [Fact]`);
    lines.push(`    public void ${methodName}()`);
    lines.push(`    {`);
    if (t.given.length > 0) {
      lines.push(`        // given:`);
      for (const g of t.given) lines.push(`        //   - ${g}`);
    }
    lines.push(`        // when: ${t.when}`);
    lines.push(`        // then: ${t.then}`);
    lines.push(`        throw new System.NotImplementedException();`);
    lines.push(`    }`);
    lines.push("");
  }
  lines.push(`}`);
  lines.push("");
  return lines.join("\n");
}

