vscode:
  extensions:
    - Vue.volar
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
    - ms-playwright.playwright
  settings:
    "[vue]":
      editor.defaultFormatter: esbenp.prettier-vscode
    "[typescript]":
      editor.defaultFormatter: esbenp.prettier-vscode
    "vue.server.hybridMode": true
    "typescript.tsdk": "node_modules/typescript/lib"
devcontainer:
  features:
    "ghcr.io/devcontainers/features/node:1":
      version: "${frontend.node_version}"
